include: package:lint/analysis_options.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    sort_unnamed_constructors_first: ignore
  exclude:
    - lib/**.g.dart
    - lib/**.freezed.dart

linter:
  rules:
    exclude:
      - avoid_positional_boolean_parameters